-- Phase 3 approved unused-index drops.
-- Generated by TRR-Backend/scripts/db/unused_index_evidence_report.py.
-- Source: /var/folders/hj/v87ntlg10vqc_sbhpq9ypy5w0000gn/T/tmp.cC8KtXiruH
-- Execute manually with owner approval. Do not wrap DROP INDEX CONCURRENTLY in an explicit transaction.

-- owner: survey/public app owner
-- table: "public"."flashback_sessions"
-- index: "public"."idx_flashback_sessions_quiz"
-- approval_reason: Owner requested flashback game removal for now; no runtime reader for public.flashback_sessions found; live table empty; parent delete FK lookup risk accepted because feature is not set up
-- approved_by: Thomas Hulihan owner approval via Codex 2026-04-28
-- reviewed_routes_or_jobs: TRR-APP flashback disabled/admin route tests; rg flashback_sessions runtime review; live constraints/index stats
-- stats_window_checked_at: 2026-04-28T05:37:38Z stats_reset=2025-12-05 20:00:25.270075+00
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_flashback_sessions_quiz";

-- owner: survey/public app owner
-- table: "public"."flashback_sessions"
-- index: "public"."idx_flashback_sessions_user"
-- approval_reason: Owner requested flashback game removal for now; no runtime reader for public.flashback_sessions found; live table empty; retained unique user_id_quiz_id prefix covers user lookup rollback path
-- approved_by: Thomas Hulihan owner approval via Codex 2026-04-28
-- reviewed_routes_or_jobs: TRR-APP flashback disabled/admin route tests; rg flashback_sessions runtime review; live constraints/index stats
-- stats_window_checked_at: 2026-04-28T05:37:38Z stats_reset=2025-12-05 20:00:25.270075+00
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_flashback_sessions_user";

-- Rollback SQL captured in owner packets:

-- rollback for "public"."idx_flashback_sessions_quiz":
-- CREATE INDEX idx_flashback_sessions_quiz ON public.flashback_sessions USING btree (quiz_id);

-- rollback for "public"."idx_flashback_sessions_user":
-- CREATE INDEX idx_flashback_sessions_user ON public.flashback_sessions USING btree (user_id);
