-- Phase 3 approved unused-index drops.
-- Generated by TRR-Backend/scripts/db/unused_index_evidence_report.py.
-- Source: ../docs/workspace/unused-index-owner-review-2026-04-28
-- Execute manually with owner approval. Do not wrap DROP INDEX CONCURRENTLY in an explicit transaction.

-- owner: admin tooling owner
-- table: "admin"."brand_logo_assets"
-- index: "admin"."brand_logo_assets_sha_idx"
-- approval_reason: No current backend route/job filters admin.brand_logo_assets by hosted_logo_sha256; logo reads use target_type/target_key/source_url/id paths and live planner used brand_logo_assets_target_idx for representative list reads.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: /api/v1/admin/brands/logos, /api/v1/admin/brands/logos/options, api/routers/admin_scrape.py manual brand logo upsert, hosted_logo_sha256 rg review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."brand_logo_assets_sha_idx";

-- owner: admin tooling owner
-- table: "admin"."cast_photo_people_tags"
-- index: "admin"."cast_photo_people_tags_people_names_idx"
-- approval_reason: Current cast-photo tag reads use cast_photo_id or people_ids containment; no route/job filters admin.cast_photo_people_tags by people_names, and live plans use cast/source or people_ids indexes.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: /api/v1/admin/cast-photos/tags, /api/v1/admin/cast-photos/tags/photo-ids, trr_backend/repositories/cast_photo_tags.py, people_names rg review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."cast_photo_people_tags_people_names_idx";

-- owner: admin tooling owner
-- table: "admin"."entity_logo_imports"
-- index: "admin"."entity_logo_imports_target_idx"
-- approval_reason: admin.entity_logo_imports is currently write-only audit evidence in backend code; no current route/job reads by target_type/target_id/created_at.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: api/routers/admin_show_sync.py _upsert_logo_import_audit, entity_logo_imports rg review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."entity_logo_imports_target_idx";

-- owner: admin tooling owner
-- table: "admin"."network_streaming_completion_attempts"
-- index: "admin"."network_streaming_completion_attempts_run_idx"
-- approval_reason: Completion attempts are inserted for diagnostics, but current backend/sync code does not read attempts by run_id; completion_id FK support remains on network_streaming_completion_attempts_completion_idx.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: scripts/sync/sync_networks_streaming_links.py attempt insert/load paths, admin network/streaming routes, live constraint/index review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."network_streaming_completion_attempts_run_idx";

-- owner: admin tooling owner
-- table: "admin"."network_streaming_discovery_state"
-- index: "admin"."network_streaming_discovery_state_updated_idx"
-- approval_reason: Discovery state is read/upserted by entity_type/entity_key/source primary key; no current route/job orders or filters by updated_at.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: scripts/sync/sync_networks_streaming_links.py discovery-state load/upsert paths and live pkey EXPLAIN
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."network_streaming_discovery_state_updated_idx";

-- owner: admin tooling owner
-- table: "admin"."network_streaming_logo_assets"
-- index: "admin"."network_streaming_logo_assets_sha_idx"
-- approval_reason: No current backend route/job filters admin.network_streaming_logo_assets by hosted_logo_sha256; detail/list paths use entity, id, source_url, and run indexes, with live detail EXPLAIN using network_streaming_logo_assets_entity_idx.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: /api/v1/admin/networks-streaming/*, /api/v1/admin/brands/logos/options, scripts/sync/sync_networks_streaming_links.py, hosted_logo_sha256 rg review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."network_streaming_logo_assets_sha_idx";

-- owner: admin tooling owner
-- table: "admin"."network_streaming_sync_runs"
-- index: "admin"."network_streaming_sync_runs_finished_idx"
-- approval_reason: Sync runs are loaded/upserted by run_id primary key for resume/state; no current route/job reads by finished_at ordering.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: scripts/sync/sync_networks_streaming_links.py sync-run load/upsert/resume paths and live pkey EXPLAIN
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."network_streaming_sync_runs_finished_idx";

-- owner: admin tooling owner
-- table: "admin"."person_cover_photos"
-- index: "admin"."idx_person_cover_photos_photo"
-- approval_reason: Current cover-photo reads join or fetch by person_id primary key; no current backend route/job reads admin.person_cover_photos by photo_id.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: trr_backend/repositories/admin_people_reads.py, trr_backend/repositories/admin_show_reads.py, live person_cover_photos_pkey EXPLAIN
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."idx_person_cover_photos_photo";

-- owner: admin tooling owner
-- table: "admin"."person_reprocess_job_events"
-- index: "admin"."idx_person_reprocess_job_events_job_created"
-- approval_reason: No current backend route/job reads or writes admin.person_reprocess_job_events; table is empty, and the remaining unique(job_id,event_index) index still starts with job_id for FK-style lookups.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: admin_person_reprocess_images rg review, live row-count/constraint/index review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."idx_person_reprocess_job_events_job_created";

-- owner: admin tooling owner
-- table: "admin"."person_reprocess_jobs"
-- index: "admin"."idx_person_reprocess_jobs_status_created"
-- approval_reason: No current backend route/job reads or writes admin.person_reprocess_jobs by status/created_at; table is empty and person_id FK helper is retained.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: admin_person_reprocess_images rg review, live row-count/constraint/index review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."idx_person_reprocess_jobs_status_created";

-- owner: admin tooling owner
-- table: "admin"."season_cast_survey_roles"
-- index: "admin"."idx_season_cast_survey_roles_person"
-- approval_reason: No current backend route/job reads or writes admin.season_cast_survey_roles by person_id; table is empty and no FK depends on this index.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: season_cast_survey_roles rg review and live row-count/constraint/index review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."idx_season_cast_survey_roles_person";

-- owner: admin tooling owner
-- table: "admin"."season_cast_survey_roles"
-- index: "admin"."idx_season_cast_survey_roles_show_season"
-- approval_reason: No current backend route/job reads or writes admin.season_cast_survey_roles by show/season; table is empty and the unique(trr_show_id,season_number,person_id) index remains as a prefix-compatible rollback-free access path.
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: season_cast_survey_roles rg review, live row-count/constraint/index review, unique-prefix review
-- stats_window_checked_at: 2026-04-28T06:27:30Z
DROP INDEX CONCURRENTLY IF EXISTS "admin"."idx_season_cast_survey_roles_show_season";

-- owner: pipeline owner
-- table: "pipeline"."run_stages"
-- index: "pipeline"."pipeline_run_stages_run_id_idx"
-- approval_reason: Redundant with run_stages_run_id_stage_name_key for run_id-prefix lookups; live pipeline.run_stages is empty; stats reset 2025-12-05; targeted pipeline tests passed
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: trr_backend.pipeline.repository fetch_run_with_stages/get_stage_prior_state/ensure_run_stages; tests/pipeline suite; live EXPLAIN
-- stats_window_checked_at: 2026-04-28T05:09:51Z
DROP INDEX CONCURRENTLY IF EXISTS "pipeline"."pipeline_run_stages_run_id_idx";

-- owner: pipeline owner
-- table: "pipeline"."run_stages"
-- index: "pipeline"."pipeline_run_stages_status_idx"
-- approval_reason: No repository/API code filters pipeline.run_stages by status; live pipeline.run_stages is empty; stats reset 2025-12-05; targeted pipeline tests passed
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: trr_backend.pipeline.repository; tests/pipeline suite; live EXPLAIN
-- stats_window_checked_at: 2026-04-28T05:09:51Z
DROP INDEX CONCURRENTLY IF EXISTS "pipeline"."pipeline_run_stages_status_idx";

-- owner: pipeline owner
-- table: "pipeline"."runs"
-- index: "pipeline"."pipeline_runs_status_idx"
-- approval_reason: No repository/API code filters pipeline.runs by status; list_runs uses created_at ordering and live EXPLAIN uses pipeline_runs_created_at_idx; live pipeline.runs is empty; targeted pipeline tests passed
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: trr_backend.pipeline.repository list_runs/update_run/create_run; tests/pipeline suite; live EXPLAIN
-- stats_window_checked_at: 2026-04-28T05:09:51Z
DROP INDEX CONCURRENTLY IF EXISTS "pipeline"."pipeline_runs_status_idx";

-- owner: pipeline owner
-- table: "pipeline"."socialblade_growth_data"
-- index: "pipeline"."socialblade_growth_data_person_platform_account_handle_idx"
-- approval_reason: Known repository/API lookup plans use socialblade_growth_data_platform_account_handle_idx and socialblade_growth_data_person_id_instagram_handle_key; candidate has zero scans since stats reset 2025-12-05; targeted SocialBlade/pipeline tests passed
-- approved_by: Codex live/static review for Thomas Hulihan
-- reviewed_routes_or_jobs: trr_backend.repositories.socialblade_growth; api/routers/socials.py SocialBlade lookup; live EXPLAIN; pipeline tests
-- stats_window_checked_at: 2026-04-28T05:09:51Z
DROP INDEX CONCURRENTLY IF EXISTS "pipeline"."socialblade_growth_data_person_platform_account_handle_idx";

-- owner: survey/public app owner
-- table: "public"."flashback_sessions"
-- index: "public"."idx_flashback_sessions_quiz"
-- approval_reason: Owner requested flashback game removal for now; no runtime reader for public.flashback_sessions found; live table empty; parent delete FK lookup risk accepted because feature is not set up
-- approved_by: Thomas Hulihan owner approval via Codex 2026-04-28
-- reviewed_routes_or_jobs: TRR-APP flashback disabled/admin route tests; rg flashback_sessions runtime review; live constraints/index stats
-- stats_window_checked_at: 2026-04-28T05:37:38Z stats_reset=2025-12-05 20:00:25.270075+00
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_flashback_sessions_quiz";

-- owner: survey/public app owner
-- table: "public"."flashback_sessions"
-- index: "public"."idx_flashback_sessions_user"
-- approval_reason: Owner requested flashback game removal for now; no runtime reader for public.flashback_sessions found; live table empty; retained unique user_id_quiz_id prefix covers user lookup rollback path
-- approved_by: Thomas Hulihan owner approval via Codex 2026-04-28
-- reviewed_routes_or_jobs: TRR-APP flashback disabled/admin route tests; rg flashback_sessions runtime review; live constraints/index stats
-- stats_window_checked_at: 2026-04-28T05:37:38Z stats_reset=2025-12-05 20:00:25.270075+00
DROP INDEX CONCURRENTLY IF EXISTS "public"."idx_flashback_sessions_user";

-- Rollback SQL captured in owner packets:

-- rollback for "admin"."brand_logo_assets_sha_idx":
-- CREATE INDEX brand_logo_assets_sha_idx ON admin.brand_logo_assets USING btree (hosted_logo_sha256);

-- rollback for "admin"."cast_photo_people_tags_people_names_idx":
-- CREATE INDEX cast_photo_people_tags_people_names_idx ON admin.cast_photo_people_tags USING gin (people_names);

-- rollback for "admin"."entity_logo_imports_target_idx":
-- CREATE INDEX entity_logo_imports_target_idx ON admin.entity_logo_imports USING btree (target_type, target_id, created_at DESC);

-- rollback for "admin"."network_streaming_completion_attempts_run_idx":
-- CREATE INDEX network_streaming_completion_attempts_run_idx ON admin.network_streaming_completion_attempts USING btree (run_id, attempted_at DESC);

-- rollback for "admin"."network_streaming_discovery_state_updated_idx":
-- CREATE INDEX network_streaming_discovery_state_updated_idx ON admin.network_streaming_discovery_state USING btree (updated_at DESC);

-- rollback for "admin"."network_streaming_logo_assets_sha_idx":
-- CREATE INDEX network_streaming_logo_assets_sha_idx ON admin.network_streaming_logo_assets USING btree (hosted_logo_sha256);

-- rollback for "admin"."network_streaming_sync_runs_finished_idx":
-- CREATE INDEX network_streaming_sync_runs_finished_idx ON admin.network_streaming_sync_runs USING btree (finished_at DESC);

-- rollback for "admin"."idx_person_cover_photos_photo":
-- CREATE INDEX idx_person_cover_photos_photo ON admin.person_cover_photos USING btree (photo_id);

-- rollback for "admin"."idx_person_reprocess_job_events_job_created":
-- CREATE INDEX idx_person_reprocess_job_events_job_created ON admin.person_reprocess_job_events USING btree (job_id, created_at);

-- rollback for "admin"."idx_person_reprocess_jobs_status_created":
-- CREATE INDEX idx_person_reprocess_jobs_status_created ON admin.person_reprocess_jobs USING btree (status, created_at DESC);

-- rollback for "admin"."idx_season_cast_survey_roles_person":
-- CREATE INDEX idx_season_cast_survey_roles_person ON admin.season_cast_survey_roles USING btree (person_id);

-- rollback for "admin"."idx_season_cast_survey_roles_show_season":
-- CREATE INDEX idx_season_cast_survey_roles_show_season ON admin.season_cast_survey_roles USING btree (trr_show_id, season_number);

-- rollback for "pipeline"."pipeline_run_stages_run_id_idx":
-- CREATE INDEX pipeline_run_stages_run_id_idx ON pipeline.run_stages USING btree (run_id);

-- rollback for "pipeline"."pipeline_run_stages_status_idx":
-- CREATE INDEX pipeline_run_stages_status_idx ON pipeline.run_stages USING btree (status);

-- rollback for "pipeline"."pipeline_runs_status_idx":
-- CREATE INDEX pipeline_runs_status_idx ON pipeline.runs USING btree (status);

-- rollback for "pipeline"."socialblade_growth_data_person_platform_account_handle_idx":
-- CREATE INDEX socialblade_growth_data_person_platform_account_handle_idx ON pipeline.socialblade_growth_data USING btree (person_id, platform, account_handle);

-- rollback for "public"."idx_flashback_sessions_quiz":
-- CREATE INDEX idx_flashback_sessions_quiz ON public.flashback_sessions USING btree (quiz_id);

-- rollback for "public"."idx_flashback_sessions_user":
-- CREATE INDEX idx_flashback_sessions_user ON public.flashback_sessions USING btree (user_id);
