#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_KEYS = (
    "TRR_DB_DIRECT_URL",
    "TRR_DB_SESSION_URL",
    "TRR_DB_URL",
    "TRR_DB_TRANSACTION_URL",
    "TRR_DB_RUNTIME_LANE",
    "TRR_DB_TRANSACTION_FLIGHT_TEST",
    "TRR_DB_FALLBACK_URL",
    "DATABASE_URL",
    "SUPABASE_DB_URL",
    "POSTGRES_POOL_MAX",
    "POSTGRES_MAX_CONCURRENT_OPERATIONS",
    "POSTGRES_APPLICATION_NAME",
    "TRR_DB_APPLICATION_NAME",
    "TRR_CORE_SUPABASE_URL",
    "TRR_CORE_SUPABASE_SERVICE_ROLE_KEY",
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
)


@dataclass(frozen=True)
class EnvSurface:
    label: str
    path: Path | None


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        values[key] = value
    return values


def _classify_connection(value: str) -> str:
    try:
        parsed = urlparse(value)
    except ValueError:
        return "present-redacted"
    host = (parsed.hostname or "").lower()
    port = parsed.port
    scheme = (parsed.scheme or "").lower()
    if scheme not in {"postgres", "postgresql", "http", "https"}:
        return "present-redacted"
    if host in {"localhost", "127.0.0.1", "::1"}:
        return f"local:{port or 'default'}"
    if host.endswith("pooler.supabase.com"):
        if port == 5432:
            return "supavisor-session:5432"
        if port == 6543:
            return "supavisor-transaction:6543"
        return f"supavisor-other:{port or 'unknown'}"
    if host.endswith(".supabase.co"):
        return f"supabase-direct-or-api:{port or 'default'}"
    if host:
        return f"other-host:{port or 'default'}"
    return "present-redacted"


def _classify_value(key: str, value: str | None) -> str:
    if value is None or value == "":
        return "absent"
    if key.endswith("_URL") or key in {"DATABASE_URL", "SUPABASE_DB_URL"}:
        return _classify_connection(value)
    if key.endswith("_KEY") or "SECRET" in key or "TOKEN" in key:
        return "present-redacted-secret"
    if re.search(r"(password|secret|token|key=|://|@)", value, re.IGNORECASE):
        return "present-redacted-sensitive"
    return value if len(value) <= 64 else "present-redacted-long"


def _default_surfaces() -> list[EnvSurface]:
    return [
        EnvSurface("TRR-APP local", ROOT / "TRR-APP/apps/web/.env.local"),
        EnvSurface("TRR-APP example", ROOT / "TRR-APP/apps/web/.env.example"),
        EnvSurface("TRR-Backend local", ROOT / "TRR-Backend/.env"),
        EnvSurface("TRR-Backend example", ROOT / "TRR-Backend/.env.example"),
        EnvSurface("process env", None),
    ]


def _render_markdown(surfaces: list[EnvSurface], keys: list[str]) -> str:
    lines = [
        "# Redacted Env Inventory",
        "",
        "Generated by `scripts/redact-env-inventory.py`. Values are intentionally shape-only.",
        "",
        "| Surface | Variable | Presence | Shape |",
        "|---|---|---|---|",
    ]
    for surface in surfaces:
        values = os.environ if surface.path is None else _parse_env_file(surface.path)
        for key in keys:
            raw_value = values.get(key)
            presence = "present" if raw_value else "absent"
            lines.append(f"| {surface.label} | `{key}` | {presence} | `{_classify_value(key, raw_value)}` |")
    return "\n".join(lines) + "\n"


def _parse_surface(value: str) -> EnvSurface:
    label, separator, raw_path = value.partition("=")
    if not separator:
        path = Path(value)
        return EnvSurface(str(path), path)
    path = Path(raw_path)
    return EnvSurface(label, path)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render redacted, shape-only env inventory.")
    parser.add_argument("--surface", action="append", default=[], help="Label=path env surface. May repeat.")
    parser.add_argument("--key", action="append", default=[], help="Env key to include. May repeat.")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true", help="Fail if rendered output differs from --output.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    surfaces = [_parse_surface(item) for item in args.surface] if args.surface else _default_surfaces()
    keys = args.key if args.key else list(DEFAULT_KEYS)
    rendered = _render_markdown(surfaces, keys)
    if args.output:
        output = args.output if args.output.is_absolute() else ROOT / args.output
        if args.check:
            existing = output.read_text(encoding="utf-8") if output.is_file() else ""
            if existing != rendered:
                print(f"[redact-env-inventory] ERROR: {output} is stale.", file=sys.stderr)
                return 1
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        return 0
    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
