#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_SCRIPT="$ROOT/scripts/dev-workspace.sh"
OUT_FILE="$ROOT/docs/workspace/env-contract.md"

MODE="${1:---generate}"
if [[ "$MODE" != "--generate" && "$MODE" != "--check" ]]; then
  echo "Usage: $0 [--generate|--check]" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_FILE")"

extract_var_rows() {
  grep -E '^[A-Z][A-Z0-9_]*="\$\{[A-Z0-9_]+:-[^}]*\}"' "$DEV_SCRIPT" \
    | sed -E 's/^([A-Z0-9_]+)="\$\{[A-Z0-9_]+:-([^}]*)\}".*/\1\t\2/' \
    | awk -F '\t' '!seen[$1]++' \
    | sort
}

visibility_tier() {
  local key="$1"
  case "$key" in
    WORKSPACE_OPEN_BROWSER|WORKSPACE_OPEN_SCREENALYTICS_TABS|WORKSPACE_CLEAN_NEXT_CACHE|WORKSPACE_BROWSER_TAB_SYNC_MODE|WORKSPACE_SCREENALYTICS|WORKSPACE_SCREENALYTICS_SKIP_DOCKER|WORKSPACE_TRR_JOB_PLANE_MODE|WORKSPACE_TRR_REMOTE_WORKERS_ENABLED|TRR_BACKEND_RELOAD)
      echo "common"
      ;;
    WORKSPACE_*)
      echo "advanced"
      ;;
    *)
      echo "internal"
      ;;
  esac
}

accepted_values() {
  local key="$1"
  case "$key" in
    *MODE)
      if [[ "$key" == "WORKSPACE_TRR_JOB_PLANE_MODE" ]]; then
        echo '`local` or `remote`'
      else
        echo "string"
      fi
      ;;
    *PORT)
      echo "integer port"
      ;;
    *TIMEOUT*|*INTERVAL*|*WORKERS|*RETRIES)
      echo "integer"
      ;;
    *ENABLED|*AUTO_RESTART|*SKIP_DOCKER|*FORCE_KILL_PORT_CONFLICTS|*CLEAN_NEXT_CACHE|*OPEN_BROWSER|*OPEN_SCREENALYTICS_TABS|*RELOAD|*REQUIRE_REDIS_FOR_MULTI_WORKER|*LONG_JOB_ENFORCE_REMOTE|*STRICT)
      echo '`0` or `1`'
      ;;
    *)
      echo "string"
      ;;
  esac
}

description_for() {
  local key="$1"
  case "$key" in
    WORKSPACE_SCREENALYTICS)
      echo "Enable or disable screenalytics service startup in workspace dev mode."
      ;;
    WORKSPACE_SCREENALYTICS_SKIP_DOCKER)
      echo "Use screenalytics without local Docker infra (Redis/MinIO bypass mode)."
      ;;
    WORKSPACE_OPEN_BROWSER)
      echo "Enable automatic browser tab sync/open after startup."
      ;;
    WORKSPACE_OPEN_SCREENALYTICS_TABS)
      echo "Include screenalytics tabs in browser sync flow."
      ;;
    WORKSPACE_BROWSER_TAB_SYNC_MODE)
      echo 'Tab synchronization strategy (`reuse_no_reload`, `reload_first`, `reload_all`).'
      ;;
    WORKSPACE_TRR_JOB_PLANE_MODE)
      echo 'Long-job ownership mode (`local` API-owned or `remote` worker-owned).'
      ;;
    WORKSPACE_TRR_REMOTE_WORKERS_ENABLED)
      echo "Start remote worker claim loops for admin/reddit/google-news jobs."
      ;;
    TRR_BACKEND_RELOAD)
      echo "Enable backend reload mode (1) instead of non-reload server mode (0)."
      ;;
    *)
      echo 'Workspace runtime variable consumed by `scripts/dev-workspace.sh`.'
      ;;
  esac
}

used_by() { echo '`scripts/dev-workspace.sh`, `Makefile`'; }

generate_contract() {
  local out="$1"
  {
    echo "# Workspace Environment Contract"
    echo
    echo 'This file is generated by `scripts/workspace-env-contract.sh`.'
    echo
    echo "Visibility tiers:"
    echo '- `common`: frequently used day-to-day toggles'
    echo '- `advanced`: less common tuning and troubleshooting controls'
    echo '- `internal`: runtime/plumbing variables usually left at defaults'
    echo
    echo "| Variable | Default | Accepted Values | Used By | Visibility | Notes |"
    echo "|---|---|---|---|---|---|"

    while IFS=$'\t' read -r key default_value; do
      [[ -z "$key" ]] && continue
      printf '| `%s` | `%s` | %s | %s | `%s` | %s |\n' \
        "$key" \
        "$default_value" \
        "$(accepted_values "$key")" \
        "$(used_by "$key")" \
        "$(visibility_tier "$key")" \
        "$(description_for "$key")"
    done < <(extract_var_rows)
  } > "$out"
}

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

generate_contract "$TMP_FILE"

if [[ "$MODE" == "--generate" ]]; then
  if [[ ! -f "$OUT_FILE" ]] || ! cmp -s "$TMP_FILE" "$OUT_FILE"; then
    mv "$TMP_FILE" "$OUT_FILE"
    echo "[env-contract] Wrote $OUT_FILE"
  else
    echo "[env-contract] No changes ($OUT_FILE is up to date)"
  fi
  exit 0
fi

if [[ ! -f "$OUT_FILE" ]]; then
  echo "[env-contract] ERROR: missing $OUT_FILE" >&2
  echo "[env-contract] Run: make env-contract" >&2
  exit 1
fi

if ! cmp -s "$TMP_FILE" "$OUT_FILE"; then
  echo "[env-contract] ERROR: $OUT_FILE is out of date." >&2
  echo "[env-contract] Run: make env-contract" >&2
  exit 1
fi

echo "[env-contract] OK"
